version: "3.9"

services:
  postgres_db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../mini_market/.env
    restart: always

  backend:
    build:
      context: ../
    restart: always
    volumes:
      - static_value:/apps/market/static/
    command: poetry run gunicorn mini_market.wsgi:application --bind 0:8000
    depends_on:
      - postgres_db
    env_file:
      - ../mini_market/.env

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend

  redis_db:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis_data:/data

  celery:
    restart: always
    build:
      context: ../
    env_file:
      - ../mini_market/.env
    command: poetry run celery -A mini_market worker -B -l INFO
    depends_on:
      - backend
      - redis_db

volumes:
  static_value:
  postgres_data:
  redis_data:
